app/adminsmart/views/urls.py
from django.urls import include, path

from .index import index
from .modules.clientes import *

urlpatterns = [


	# Custom Views
    path('', index, name='index'),
	path('home/', ClientesView.as_view(), name='home'),
	path('cuentas-a-cobrar/', ClientesView.as_view(), name='clientes'),
	path('cuentas-a-pagar/', ClientesView.as_view(), name='proveedores'),
	path('tesoreria/', ClientesView.as_view(), name='tesoreria'),
	path('contabilidad/', ClientesView.as_view(), name='contabilidad'),
	path('informes/', ClientesView.as_view(), name='informes'),
	path('configuracion/', ClientesView.as_view(), name='configuracion'),

]

app/config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView

from .views import ready


urlpatterns = [
	# Django Admin
	path(settings.ADMIN_URL, admin.site.urls),

	# K8s
	path('ready/', ready),
	
	# API
	path('users/', include(('users.urls', 'users'), namespace='users')),
	path('utils/', include(('utils.urls', 'utils'), namespace='utils')),
	path('operative/', include(('core.urls', 'operative'), namespace='operative')),
	# Views
	# ## Authentication
	# path('recuperar-pass/', include('django.contrib.auth.urls')),
    # path('login/', LoginView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),
	# path('signup/', LoginView.as_view(), name='signup'),

	# ## Frontend
	# path('', include(('front.urls', 'views'), namespace='front')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

app/core/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views.parametros import ParametrosViewSet
from .views.reportes import ReportesViewSet
from .views.comprobantes import ComprobantesViewSet

router = DefaultRouter()
router.register(r'parametros/(?P<naturaleza>[-a-zA-Z0-0_]+)', ParametrosViewSet, basename='operative')

router.register(r'comprobantes', ComprobantesViewSet, basename='operative')

router.register(r'reportes/(?P<tipo>[-a-zA-Z0-0_]+)', ReportesViewSet, basename='operative')

urlpatterns = [
     path('', include(router.urls))
]

app/users/models/perfiles.py
"""Perfil model."""

# Django
from django.db import models
from django.core.validators import RegexValidator
from django_afip.models import DocumentType
# Utilities
from utils.models import BaseModel


class Perfil(BaseModel):
    """
		Modelo de perfil para cualquier persona (Fisica o Juridica), Cliente, Socio, Proveedores y para Lotes
	"""

    users = models.ManyToManyField('users.User', blank=True)
    nombre = models.CharField(max_length=160, blank=True, null=True)
    razon_social = models.CharField(max_length=80, blank=True, null=True)
    tipo_documento = models.ForeignKey(DocumentType, blank=True, null=True, on_delete=models.SET_NULL)
    numero_documento = models.CharField(max_length=13)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    es_extranjero = models.BooleanField(default=False)
    mail = models.EmailField(blank=True, null=True, max_length=254)
    domicilio = models.ForeignKey("utils.Domicilio", blank=True, null=True, on_delete=models.SET_NULL)
    telefono = models.CharField(max_length=17, blank=True)
    comunidades = models.ManyToManyField("utils.Comunidad", blank=True, related_name="admins")

    def __str__(self):
        if self.razon_social:
            return self.razon_social
        return self.nombre

    def get_emails_destinatarios(self):
        destinatarios = []
        [destinatarios.append(email) for email in [self.mail] + list(self.users.all().values_list('email', flat=True))
         if (email and not email in destinatarios)]
        return destinatarios

app/adminsmart/templates/raiz.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block titulo %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="shortcut icon" href='{% static "anopa/images/favicon.svg" %}'>

    <link href='{% static "plugins/jquery-toastr/jquery.toast.min.css" %}' rel="stylesheet" type="text/css" />

    <link href='{% static "assets/css/bootstrap.min.css" %}' rel="stylesheet" type="text/css" />
    <link href='{% static "assets/css/core.css" %}' rel="stylesheet" type="text/css" />
    <link href='{% static "assets/css/components.css" %}' rel="stylesheet" type="text/css" />
    <link href='{% static "assets/css/icons.css" %}' rel="stylesheet" type="text/css" />
    <link href='{% static "assets/css/pages.css" %}' rel="stylesheet" type="text/css" />
    <link href='{% static "assets/css/menu.css" %}' rel="stylesheet" type="text/css" />
    <link href='{% static "assets/css/responsive.css" %}' rel="stylesheet" type="text/css" />
    <link href='{% static "anopa/anopa.css" %}' rel="stylesheet" type="text/css" />

    {% block css %}{% endblock %}


    <script src='{% static "assets/js/modernizr.min.js" %}'></script>

  </head>


  <body>
    <div class="se-pre-con"></div>

    <header id="topnav">
      <div class="topbar-main">
          <div class="container">

            <div class="logo">

                <a href="{% url 'front:home' %}" class="logo">
                  <img src='{% static "anopa/images/icono.svg" %}' alt="" height="40"> <small>{{ comunidad }}</small>
                </a>
            </div>

            <div class="menu-extras">

              <ul class="nav navbar-nav navbar-right pull-right">

                <li class="dropdown navbar-c-items">
                    <a href="" class="dropdown-toggle waves-effect profile" data-toggle="dropdown" aria-expanded="true"><img src="{% static 'assets/images/icons/assistant.svg' %}" alt="user-img" class="img-circle"> </a>
                    <ul class="dropdown-menu dropdown-menu-right arrow-dropdown-menu arrow-menu-right user-list notify-list">
                        <li class="text-center">
                            <h5>Hola, {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}</h5>
                        </li>
                        <li><a href="a"><i class="dripicons-user m-r-10"></i> Perfil</a></li>
                        <li>
                          <select name="select_comunidad" id="select_comunidad">
                            {% for com in user.perfil_set.first.comunidades.all %}
                              <option value="{{com.id}}">{{com.nombre}}</option>
                            {% endfor %}
                          </select>
                          
                        </li>
                        <li><a href="a"><i class="dripicons-bookmark m-r-10"></i> Biblioteca</a></li>
                        <li><a href="{% url 'logout' %}"><i class="dripicons-power m-r-10"></i> Logout</a></li>
                    </ul>

                </li>
              </ul>

              <div class="menu-item">
                  <a class="navbar-toggle">
                      <div class="lines">
                          <span></span>
                          <span></span>
                          <span></span>
                      </div>
                  </a>
              </div>

            </div>

          </div>
      </div>

      <div class="navbar-custom">
        <div class="container">
          <div id="navigation">
            <ul class="navigation-menu">
              {% include 'sidebar/index.html' %}
            </ul>
          </div>
        </div>
      </div>
    </header>


    <div class="wrapper">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <div class="page-title-box">
                {% block breadcrum %}{% endblock %}
                <h4 class="page-title">{% block header %}{% endblock %}</h4>
              </div>
              {% if validacion_demo %}
                <div class="alert alert-icon alert-white alert-warning alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <i class="mdi mdi-alert"></i>
                    Algunas funcionalidades estan deshabilitadas para este usuario.
                </div>
              {% endif %}
            </div>
          </div>
          {% block content %}{% endblock %}
        </div>


        <footer class="footer text-right">
          <div class="container">
            <div class="row">
              <div class="col-xs-12 text-center">
                  Website by <b>AdminSmart</b>
              </div>
            </div>
          </div>
        </footer>

    </div>

    <script src='{% static "assets/js/jquery.min.js" %}'></script>
    <script src='{% static "assets/js/bootstrap.min.js" %}'></script>
    <script src='{% static "assets/js/waves.js" %}'></script>
    <script src='{% static "assets/js/jquery.slimscroll.js" %}'></script>
    <script src='{% static "plugins/waypoints/jquery.waypoints.min.js" %}'></script>
    <script src='{% static "plugins/counterup/jquery.counterup.min.js" %}'></script>
    <script src='{% static "plugins/jquery-toastr/jquery.toast.min.js" %}'></script>
    <script src='{% static "anopa/anopa.js" %}'></script>
    {% block js %}{% endblock %}
    <script src='{% static "assets/js/jquery.core.js" %}'></script>
    <script src='{% static "assets/js/jquery.app.js" %}'></script>
    <script src='{% static "plugins/jquery-validation/jquery.validate.js" %}'></script>
    <script src='{% static "plugins/jquery-validation/localization/messages_es.js" %}'></script>
    {% if messages %}
        <script>
          {% for message in messages %}
            $(document).ready(function(){
              $.toast({
                  heading: '{% if message.tags == "success" %}Bien hecho!{% else %}Ups!{% endif %}',
                  text: '{{message}}',
                  position: 'top-right',
                  loaderBg: '{% if message.tags == "success" %}#5ba035{%else%}#bf441d{% endif %}',
                  icon: '{{message.tags}}',
                  hideAfter: 6000,
                  stack: 1
              });
            });
          {% endfor %}
        </script>
    {% endif %}

  </body>
</html>